// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/friends_quest/friends_quest_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:friendsheet/data/models/friends_quest.dart' as _i2;
import 'package:friendsheet/data/repositories/friends_quest_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFriendsQuest_0 extends _i1.SmartFake implements _i2.FriendsQuest {
  _FakeFriendsQuest_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FriendsQuestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsQuestRepository extends _i1.Mock
    implements _i3.FriendsQuestRepository {
  MockFriendsQuestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.FriendsQuest> getAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue: <_i2.FriendsQuest>[],
      ) as List<_i2.FriendsQuest>);

  @override
  _i4.Future<_i2.FriendsQuest> create(
    String? userId,
    String? name,
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            userId,
            name,
            participantIds,
          ],
        ),
        returnValue: _i4.Future<_i2.FriendsQuest>.value(_FakeFriendsQuest_0(
          this,
          Invocation.method(
            #create,
            [
              userId,
              name,
              participantIds,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FriendsQuest>);

  @override
  _i4.Future<void> delete(
    String? userId,
    String? questId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            userId,
            questId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
