// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i16;
import 'package:firebase_auth/firebase_auth.dart' as _i10;
import 'package:friendsheet/data/models/activity_category.dart' as _i3;
import 'package:friendsheet/data/models/catch_up_topic.dart' as _i20;
import 'package:friendsheet/data/models/friends_quest.dart' as _i5;
import 'package:friendsheet/data/models/meeting.dart' as _i8;
import 'package:friendsheet/data/models/person.dart' as _i4;
import 'package:friendsheet/data/models/stats_data_bundle.dart' as _i2;
import 'package:friendsheet/data/repositories/activity_category_repository.dart'
    as _i11;
import 'package:friendsheet/data/repositories/cache_invalidator.dart' as _i12;
import 'package:friendsheet/data/repositories/catch_up_topic_repository.dart'
    as _i19;
import 'package:friendsheet/data/repositories/friends_quest_repository.dart'
    as _i18;
import 'package:friendsheet/data/repositories/meeting_repository.dart' as _i14;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i13;
import 'package:friendsheet/data/repositories/statistics_repository.dart'
    as _i6;
import 'package:friendsheet/data/services/auth_service.dart' as _i9;
import 'package:friendsheet/data/services/ltns_exclusion_service.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatsDataBundle_0 extends _i1.SmartFake
    implements _i2.StatsDataBundle {
  _FakeStatsDataBundle_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityCategory_1 extends _i1.SmartFake
    implements _i3.ActivityCategory {
  _FakeActivityCategory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerson_2 extends _i1.SmartFake implements _i4.Person {
  _FakePerson_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFriendsQuest_3 extends _i1.SmartFake implements _i5.FriendsQuest {
  _FakeFriendsQuest_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i6.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> invalidateMeetingsCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateMeetingsCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> invalidateCategoriesCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateCategoriesCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> invalidatePersonsCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidatePersonsCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> invalidateAllCaches() => (super.noSuchMethod(
        Invocation.method(
          #invalidateAllCaches,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<int>> getAvailableYears(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableYears,
          [userId],
        ),
        returnValue: _i7.Future<List<int>>.value(<int>[]),
      ) as _i7.Future<List<int>>);

  @override
  _i7.Future<List<_i8.Meeting>> getMeetingsForYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsForYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i7.Future<List<_i8.Meeting>>.value(<_i8.Meeting>[]),
      ) as _i7.Future<List<_i8.Meeting>>);

  @override
  _i7.Future<_i2.StatsDataBundle> loadAllStatsData(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAllStatsData,
          [
            year,
            userId,
          ],
        ),
        returnValue:
            _i7.Future<_i2.StatsDataBundle>.value(_FakeStatsDataBundle_0(
          this,
          Invocation.method(
            #loadAllStatsData,
            [
              year,
              userId,
            ],
          ),
        )),
      ) as _i7.Future<_i2.StatsDataBundle>);

  @override
  List<_i6.ActivityBreakdownEntry> computeActivityBreakdown(
          _i2.StatsDataBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeActivityBreakdown,
          [bundle],
        ),
        returnValue: <_i6.ActivityBreakdownEntry>[],
      ) as List<_i6.ActivityBreakdownEntry>);

  @override
  List<_i6.PersonActivityEntry> computePersonsForActivity(
    _i2.StatsDataBundle? bundle,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #computePersonsForActivity,
          [
            bundle,
            categoryId,
          ],
        ),
        returnValue: <_i6.PersonActivityEntry>[],
      ) as List<_i6.PersonActivityEntry>);

  @override
  List<_i6.InteractionDistributionEntry> computeInteractionDistribution(
          _i2.StatsDataBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeInteractionDistribution,
          [bundle],
        ),
        returnValue: <_i6.InteractionDistributionEntry>[],
      ) as List<_i6.InteractionDistributionEntry>);

  @override
  _i7.Future<List<_i6.ActivityBreakdownEntry>> getActivityWeightBreakdown(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityWeightBreakdown,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i6.ActivityBreakdownEntry>>.value(
            <_i6.ActivityBreakdownEntry>[]),
      ) as _i7.Future<List<_i6.ActivityBreakdownEntry>>);

  @override
  _i7.Future<List<_i6.PersonActivityEntry>> getPersonsForActivity(
    String? categoryId,
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsForActivity,
          [
            categoryId,
            year,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i6.PersonActivityEntry>>.value(
            <_i6.PersonActivityEntry>[]),
      ) as _i7.Future<List<_i6.PersonActivityEntry>>);

  @override
  _i7.Future<List<_i6.InteractionDistributionEntry>> getInteractionDistribution(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInteractionDistribution,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i6.InteractionDistributionEntry>>.value(
            <_i6.InteractionDistributionEntry>[]),
      ) as _i7.Future<List<_i6.InteractionDistributionEntry>>);

  @override
  _i7.Future<List<_i6.InteractionDistributionEntry>> getCumulativeInteractions(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCumulativeInteractions,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i6.InteractionDistributionEntry>>.value(
            <_i6.InteractionDistributionEntry>[]),
      ) as _i7.Future<List<_i6.InteractionDistributionEntry>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i10.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i7.Stream<_i10.User?>.empty(),
      ) as _i7.Stream<_i10.User?>);

  @override
  _i7.Future<_i10.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i7.Future<_i10.User?>.value(),
      ) as _i7.Future<_i10.User?>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ActivityCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityCategoryRepository extends _i1.Mock
    implements _i11.ActivityCategoryRepository {
  MockActivityCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i12.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<List<_i3.ActivityCategory>> getCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [userId],
        ),
        returnValue: _i7.Stream<List<_i3.ActivityCategory>>.empty(),
      ) as _i7.Stream<List<_i3.ActivityCategory>>);

  @override
  _i7.Future<void> addCategory(_i3.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateCategory(_i3.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCategory(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteWithChildren(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWithChildren,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.ActivityCategory> createSelectableCategory({
    required String? name,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSelectableCategory,
          [],
          {
            #name: name,
            #userId: userId,
          },
        ),
        returnValue:
            _i7.Future<_i3.ActivityCategory>.value(_FakeActivityCategory_1(
          this,
          Invocation.method(
            #createSelectableCategory,
            [],
            {
              #name: name,
              #userId: userId,
            },
          ),
        )),
      ) as _i7.Future<_i3.ActivityCategory>);

  @override
  _i7.Future<List<_i3.ActivityCategory>> getSelectableCategories(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableCategories,
          [userId],
        ),
        returnValue: _i7.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i7.Future<List<_i3.ActivityCategory>>);

  @override
  _i7.Future<List<String>> getAncestorIds(
    String? categoryId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestorIds,
          [
            categoryId,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i3.ActivityCategory>> getAllCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [userId],
        ),
        returnValue: _i7.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i7.Future<List<_i3.ActivityCategory>>);

  @override
  _i7.Future<List<_i3.ActivityCategory>> getCategoriesByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i7.Future<List<_i3.ActivityCategory>>);
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i13.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i12.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<List<_i4.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i7.Future<List<_i4.Person>>.value(<_i4.Person>[]),
      ) as _i7.Future<List<_i4.Person>>);

  @override
  _i7.Future<List<_i4.Person>> getPersonsByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i4.Person>>.value(<_i4.Person>[]),
      ) as _i7.Future<List<_i4.Person>>);

  @override
  _i7.Future<_i4.Person> addPerson(_i4.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i7.Future<_i4.Person>.value(_FakePerson_2(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i7.Future<_i4.Person>);

  @override
  _i7.Future<void> updatePerson(_i4.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isDuplicateName(
    String? userId,
    String? firstName,
    String? lastName, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateName,
          [
            userId,
            firstName,
            lastName,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> linkPartner(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkPartner,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unlinkPartner(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkPartner,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i14.MeetingRepository {
  MockMeetingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i12.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String> saveMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #saveMeeting,
          [meeting],
        ),
        returnValue: _i7.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #saveMeeting,
            [meeting],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Stream<List<_i8.Meeting>> getMeetingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByUser,
          [userId],
        ),
        returnValue: _i7.Stream<List<_i8.Meeting>>.empty(),
      ) as _i7.Stream<List<_i8.Meeting>>);

  @override
  _i7.Stream<_i16.QuerySnapshot<Object?>> getMeetingsSnapshot(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsSnapshot,
          [userId],
        ),
        returnValue: _i7.Stream<_i16.QuerySnapshot<Object?>>.empty(),
      ) as _i7.Stream<_i16.QuerySnapshot<Object?>>);

  @override
  _i7.Future<List<_i8.Meeting>> getAllMeetings(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMeetings,
          [userId],
        ),
        returnValue: _i7.Future<List<_i8.Meeting>>.value(<_i8.Meeting>[]),
      ) as _i7.Future<List<_i8.Meeting>>);

  @override
  _i7.Future<void> updateMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [meeting],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteMeeting(
    String? userId,
    String? meetingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [
            userId,
            meetingId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.Meeting>> getMeetingsByParticipant(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByParticipant,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i7.Future<List<_i8.Meeting>>.value(<_i8.Meeting>[]),
      ) as _i7.Future<List<_i8.Meeting>>);

  @override
  _i7.Future<int> getMeetingsCountForPerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsCountForPerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> replaceCategoryInMeetings(
    String? userId,
    String? sourceId,
    String? targetId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceCategoryInMeetings,
          [
            userId,
            sourceId,
            targetId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.Meeting?> getLastMeetingWithoutNotes(
    String? userId,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastMeetingWithoutNotes,
          [
            userId,
            since,
          ],
        ),
        returnValue: _i7.Future<_i8.Meeting?>.value(),
      ) as _i7.Future<_i8.Meeting?>);

  @override
  _i7.Future<List<_i8.Meeting>> getRecentMeetingsWithoutNotes(
    String? userId,
    DateTime? since, {
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMeetingsWithoutNotes,
          [
            userId,
            since,
          ],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i8.Meeting>>.value(<_i8.Meeting>[]),
      ) as _i7.Future<List<_i8.Meeting>>);

  @override
  _i7.Future<Set<String>> getPersonIdsSeenSince(
    String? userId,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonIdsSeenSince,
          [
            userId,
            since,
          ],
        ),
        returnValue: _i7.Future<Set<String>>.value(<String>{}),
      ) as _i7.Future<Set<String>>);

  @override
  _i7.Future<List<_i8.Meeting>> getRecentMeetingsByPerson(
    String? userId,
    String? personId, {
    int? limit = 4,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMeetingsByPerson,
          [
            userId,
            personId,
          ],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i8.Meeting>>.value(<_i8.Meeting>[]),
      ) as _i7.Future<List<_i8.Meeting>>);

  @override
  _i7.Future<void> removePersonFromMeetings(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePersonFromMeetings,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [LtnsExclusionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLtnsExclusionService extends _i1.Mock
    implements _i17.LtnsExclusionService {
  MockLtnsExclusionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<Set<String>> getExcludedIds() => (super.noSuchMethod(
        Invocation.method(
          #getExcludedIds,
          [],
        ),
        returnValue: _i7.Future<Set<String>>.value(<String>{}),
      ) as _i7.Future<Set<String>>);

  @override
  _i7.Future<void> setExcluded(
    String? personId, {
    required bool? excluded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExcluded,
          [personId],
          {#excluded: excluded},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [FriendsQuestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsQuestRepository extends _i1.Mock
    implements _i18.FriendsQuestRepository {
  MockFriendsQuestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.FriendsQuest> getAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue: <_i5.FriendsQuest>[],
      ) as List<_i5.FriendsQuest>);

  @override
  _i7.Future<_i5.FriendsQuest> create(
    String? userId,
    String? name,
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            userId,
            name,
            participantIds,
          ],
        ),
        returnValue: _i7.Future<_i5.FriendsQuest>.value(_FakeFriendsQuest_3(
          this,
          Invocation.method(
            #create,
            [
              userId,
              name,
              participantIds,
            ],
          ),
        )),
      ) as _i7.Future<_i5.FriendsQuest>);

  @override
  _i7.Future<void> delete(
    String? userId,
    String? questId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            userId,
            questId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateQuest(
    String? userId,
    _i5.FriendsQuest? quest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuest,
          [
            userId,
            quest,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [CatchUpTopicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatchUpTopicRepository extends _i1.Mock
    implements _i19.CatchUpTopicRepository {
  MockCatchUpTopicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> add(
    String? userId,
    String? personId,
    String? text,
    String? contextLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            userId,
            personId,
            text,
            contextLabel,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #add,
            [
              userId,
              personId,
              text,
              contextLabel,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<List<_i20.CatchUpTopic>> getActive(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [
            userId,
            personId,
          ],
        ),
        returnValue:
            _i7.Future<List<_i20.CatchUpTopic>>.value(<_i20.CatchUpTopic>[]),
      ) as _i7.Future<List<_i20.CatchUpTopic>>);

  @override
  _i7.Future<void> update(
    String? userId,
    String? personId,
    String? topicId,
    String? text,
    String? contextLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            userId,
            personId,
            topicId,
            text,
            contextLabel,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> archive(
    String? userId,
    String? personId,
    String? topicId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archive,
          [
            userId,
            personId,
            topicId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i20.CatchUpTopic>> getArchived(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchived,
          [
            userId,
            personId,
          ],
        ),
        returnValue:
            _i7.Future<List<_i20.CatchUpTopic>>.value(<_i20.CatchUpTopic>[]),
      ) as _i7.Future<List<_i20.CatchUpTopic>>);

  @override
  _i7.Future<void> mergeTopics(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeTopics,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> delete(
    String? userId,
    String? personId,
    String? topicId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            userId,
            personId,
            topicId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> applyRedistribution(
    String? userId,
    String? personId,
    String? partnerId,
    List<_i20.CatchUpTopic>? postLinkTopics,
    Map<String, _i19.TopicRedistributionDecision>? decisions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyRedistribution,
          [
            userId,
            personId,
            partnerId,
            postLinkTopics,
            decisions,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
