// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/persons/catch_up_topics_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:friendsheet/data/models/catch_up_topic.dart' as _i5;
import 'package:friendsheet/data/repositories/catch_up_topic_repository.dart'
    as _i2;
import 'package:friendsheet/data/services/auth_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CatchUpTopicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatchUpTopicRepository extends _i1.Mock
    implements _i2.CatchUpTopicRepository {
  MockCatchUpTopicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> add(
    String? userId,
    String? personId,
    String? text,
    String? contextLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            userId,
            personId,
            text,
            contextLabel,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #add,
            [
              userId,
              personId,
              text,
              contextLabel,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<_i5.CatchUpTopic>> getActive(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [
            userId,
            personId,
          ],
        ),
        returnValue:
            _i3.Future<List<_i5.CatchUpTopic>>.value(<_i5.CatchUpTopic>[]),
      ) as _i3.Future<List<_i5.CatchUpTopic>>);

  @override
  _i3.Future<void> update(
    String? userId,
    String? personId,
    String? topicId,
    String? text,
    String? contextLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            userId,
            personId,
            topicId,
            text,
            contextLabel,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> archive(
    String? userId,
    String? personId,
    String? topicId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archive,
          [
            userId,
            personId,
            topicId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CatchUpTopic>> getArchived(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchived,
          [
            userId,
            personId,
          ],
        ),
        returnValue:
            _i3.Future<List<_i5.CatchUpTopic>>.value(<_i5.CatchUpTopic>[]),
      ) as _i3.Future<List<_i5.CatchUpTopic>>);

  @override
  _i3.Future<void> mergeTopics(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeTopics,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(
    String? userId,
    String? personId,
    String? topicId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            userId,
            personId,
            topicId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> applyRedistribution(
    String? userId,
    String? personId,
    String? partnerId,
    List<_i5.CatchUpTopic>? postLinkTopics,
    Map<String, _i2.TopicRedistributionDecision>? decisions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyRedistribution,
          [
            userId,
            personId,
            partnerId,
            postLinkTopics,
            decisions,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i7.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i7.User?>.empty(),
      ) as _i3.Stream<_i7.User?>);

  @override
  _i3.Future<_i7.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i7.User?>.value(),
      ) as _i3.Future<_i7.User?>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
