// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/persons/person_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i12;
import 'package:firebase_auth/firebase_auth.dart' as _i14;
import 'package:friendsheet/data/models/meeting.dart' as _i10;
import 'package:friendsheet/data/models/person.dart' as _i2;
import 'package:friendsheet/data/models/sharing_token.dart' as _i3;
import 'package:friendsheet/data/repositories/cache_invalidator.dart' as _i7;
import 'package:friendsheet/data/repositories/meeting_repository.dart' as _i9;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i6;
import 'package:friendsheet/data/repositories/sharing_token_repository.dart'
    as _i4;
import 'package:friendsheet/data/services/auth_service.dart' as _i13;
import 'package:friendsheet/data/services/relationship_score_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePerson_0 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharingToken_1 extends _i1.SmartFake implements _i3.SharingToken {
  _FakeSharingToken_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenValidationResult_2 extends _i1.SmartFake
    implements _i4.TokenValidationResult {
  _FakeTokenValidationResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelationshipScore_3 extends _i1.SmartFake
    implements _i5.RelationshipScore {
  _FakeRelationshipScore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i6.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i7.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<List<_i2.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i8.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i8.Future<List<_i2.Person>>);

  @override
  _i8.Future<List<_i2.Person>> getPersonsByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i8.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i8.Future<List<_i2.Person>>);

  @override
  _i8.Future<_i2.Person> addPerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i8.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i8.Future<_i2.Person>);

  @override
  _i8.Future<void> updatePerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isDuplicateName(
    String? userId,
    String? firstName,
    String? lastName, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateName,
          [
            userId,
            firstName,
            lastName,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> linkPartner(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkPartner,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> unlinkPartner(
    String? userId,
    String? personId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkPartner,
          [
            userId,
            personId,
            partnerId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i9.MeetingRepository {
  MockMeetingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i7.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String> saveMeeting(_i10.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #saveMeeting,
          [meeting],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #saveMeeting,
            [meeting],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Stream<List<_i10.Meeting>> getMeetingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByUser,
          [userId],
        ),
        returnValue: _i8.Stream<List<_i10.Meeting>>.empty(),
      ) as _i8.Stream<List<_i10.Meeting>>);

  @override
  _i8.Stream<_i12.QuerySnapshot<Object?>> getMeetingsSnapshot(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsSnapshot,
          [userId],
        ),
        returnValue: _i8.Stream<_i12.QuerySnapshot<Object?>>.empty(),
      ) as _i8.Stream<_i12.QuerySnapshot<Object?>>);

  @override
  _i8.Future<List<_i10.Meeting>> getAllMeetings(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMeetings,
          [userId],
        ),
        returnValue: _i8.Future<List<_i10.Meeting>>.value(<_i10.Meeting>[]),
      ) as _i8.Future<List<_i10.Meeting>>);

  @override
  _i8.Future<void> updateMeeting(_i10.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [meeting],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteMeeting(
    String? userId,
    String? meetingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [
            userId,
            meetingId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.Meeting>> getMeetingsByParticipant(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByParticipant,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i8.Future<List<_i10.Meeting>>.value(<_i10.Meeting>[]),
      ) as _i8.Future<List<_i10.Meeting>>);

  @override
  _i8.Future<int> getMeetingsCountForPerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsCountForPerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> replaceCategoryInMeetings(
    String? userId,
    String? sourceId,
    String? targetId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceCategoryInMeetings,
          [
            userId,
            sourceId,
            targetId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i10.Meeting?> getLastMeetingWithoutNotes(
    String? userId,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastMeetingWithoutNotes,
          [
            userId,
            since,
          ],
        ),
        returnValue: _i8.Future<_i10.Meeting?>.value(),
      ) as _i8.Future<_i10.Meeting?>);

  @override
  _i8.Future<List<_i10.Meeting>> getRecentMeetingsWithoutNotes(
    String? userId,
    DateTime? since, {
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMeetingsWithoutNotes,
          [
            userId,
            since,
          ],
          {#limit: limit},
        ),
        returnValue: _i8.Future<List<_i10.Meeting>>.value(<_i10.Meeting>[]),
      ) as _i8.Future<List<_i10.Meeting>>);

  @override
  _i8.Future<Set<String>> getPersonIdsSeenSince(
    String? userId,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonIdsSeenSince,
          [
            userId,
            since,
          ],
        ),
        returnValue: _i8.Future<Set<String>>.value(<String>{}),
      ) as _i8.Future<Set<String>>);

  @override
  _i8.Future<List<_i10.Meeting>> getRecentMeetingsByPerson(
    String? userId,
    String? personId, {
    int? limit = 4,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMeetingsByPerson,
          [
            userId,
            personId,
          ],
          {#limit: limit},
        ),
        returnValue: _i8.Future<List<_i10.Meeting>>.value(<_i10.Meeting>[]),
      ) as _i8.Future<List<_i10.Meeting>>);

  @override
  _i8.Future<void> removePersonFromMeetings(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePersonFromMeetings,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i13.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i14.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i8.Stream<_i14.User?>.empty(),
      ) as _i8.Stream<_i14.User?>);

  @override
  _i8.Future<_i14.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i8.Future<_i14.User?>.value(),
      ) as _i8.Future<_i14.User?>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [SharingTokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharingTokenRepository extends _i1.Mock
    implements _i4.SharingTokenRepository {
  MockSharingTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.SharingToken> generateToken(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateToken,
          [userId],
        ),
        returnValue: _i8.Future<_i3.SharingToken>.value(_FakeSharingToken_1(
          this,
          Invocation.method(
            #generateToken,
            [userId],
          ),
        )),
      ) as _i8.Future<_i3.SharingToken>);

  @override
  _i8.Future<_i3.SharingToken?> getActiveToken(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveToken,
          [userId],
        ),
        returnValue: _i8.Future<_i3.SharingToken?>.value(),
      ) as _i8.Future<_i3.SharingToken?>);

  @override
  _i8.Future<void> deleteToken(
    String? userId,
    String? tokenId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [
            userId,
            tokenId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.TokenValidationResult> validateAndClaimToken(
          String? tokenValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAndClaimToken,
          [tokenValue],
        ),
        returnValue: _i8.Future<_i4.TokenValidationResult>.value(
            _FakeTokenValidationResult_2(
          this,
          Invocation.method(
            #validateAndClaimToken,
            [tokenValue],
          ),
        )),
      ) as _i8.Future<_i4.TokenValidationResult>);

  @override
  _i8.Future<void> markAsUsed(
    String? userId,
    String? tokenId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUsed,
          [
            userId,
            tokenId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [RelationshipScoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelationshipScoreService extends _i1.Mock
    implements _i5.RelationshipScoreService {
  MockRelationshipScoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.RelationshipScore> computeScore(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeScore,
          [
            userId,
            personId,
          ],
        ),
        returnValue:
            _i8.Future<_i5.RelationshipScore>.value(_FakeRelationshipScore_3(
          this,
          Invocation.method(
            #computeScore,
            [
              userId,
              personId,
            ],
          ),
        )),
      ) as _i8.Future<_i5.RelationshipScore>);
}
