// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/persons/persons_list_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:friendsheet/data/models/person.dart' as _i2;
import 'package:friendsheet/data/repositories/cache_invalidator.dart' as _i4;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i3;
import 'package:friendsheet/data/services/auth_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePerson_0 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i3.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i4.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i2.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i5.Future<List<_i2.Person>>);

  @override
  _i5.Future<List<_i2.Person>> getPersonsByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i5.Future<List<_i2.Person>>);

  @override
  _i5.Future<_i2.Person> addPerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i5.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i5.Future<_i2.Person>);

  @override
  _i5.Future<void> updatePerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isDuplicateName(
    String? userId,
    String? firstName,
    String? lastName, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateName,
          [
            userId,
            firstName,
            lastName,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i7.User?>.empty(),
      ) as _i5.Stream<_i7.User?>);

  @override
  _i5.Future<_i7.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i7.User?>.value(),
      ) as _i5.Future<_i7.User?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
