import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'person.freezed.dart';
part 'person.g.dart';

/// Person represents a contact that can be added as a meeting participant.
/// firstName is required, lastName is optional.
@freezed
class Person with _$Person {
  const Person._();

  const factory Person({
    /// Unique identifier generated by Firestore
    required String id,

    /// Owner's user ID — ensures data isolation between users
    required String userId,

    /// First name — always required
    required String firstName,

    /// Last name — optional, not all contacts have one
    String? lastName,

    /// Timestamp of record creation
    required DateTime createdAt,
  }) = _Person;

  /// Returns full display name.
  /// Falls back to firstName only if lastName is null or empty.
  String get fullName {
    if (lastName == null || lastName!.trim().isEmpty) {
      return firstName;
    }
    return '$firstName $lastName';
  }

  /// Creates Person from a Firestore document snapshot.
  /// Uses explicit casting to satisfy the Dart analyzer.
  factory Person.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Person(
      id: doc.id,
      userId: (data['userId'] ?? '') as String,
      firstName: (data['firstName'] ?? '') as String,
      // lastName may be absent in Firestore — treated as null
      lastName: data['lastName'] as String?,
      createdAt: (data['createdAt'] as Timestamp).toDate(),
    );
  }

  /// Creates Person from a JSON map — used in tests and local storage.
  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);

  /// Converts Person to a Firestore-compatible map.
  /// lastName is omitted when null — avoids storing empty fields.
  Map<String, dynamic> toFirestore() {
    return {
      'userId': userId,
      'firstName': firstName,
      // Only include lastName if it has a value
      if (lastName != null) 'lastName': lastName,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }

  /// Returns true if Person has minimum required data.
  bool isValid() {
    return firstName.isNotEmpty && userId.isNotEmpty;
  }
}
