import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'sharing_token.freezed.dart';
part 'sharing_token.g.dart';

/// Represents a one-time sharing token generated by user C.
/// Stored in `users/{uid}/sharing_tokens/{tokenId}`.
/// Token expires after 24 hours and can only be used once.
@freezed
class SharingToken with _$SharingToken {
  const SharingToken._();

  const factory SharingToken({
    required String id,
    required String token,
    required DateTime createdAt,
    required DateTime expiresAt,
    @Default(false) bool isUsed,
  }) = _SharingToken;

  factory SharingToken.fromJson(Map<String, dynamic> json) =>
      _$SharingTokenFromJson(json);

  factory SharingToken.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return SharingToken(
      id: doc.id,
      token: (data['token'] ?? '') as String,
      createdAt: data['createdAt'] != null
          ? (data['createdAt'] as Timestamp).toDate()
          : DateTime.fromMillisecondsSinceEpoch(0),
      expiresAt: data['expiresAt'] != null
          ? (data['expiresAt'] as Timestamp).toDate()
          : DateTime.fromMillisecondsSinceEpoch(0),
      isUsed: (data['isUsed'] ?? false) as bool,
    );
  }

  Map<String, dynamic> toFirestore() => {
        'token': token,
        'createdAt': Timestamp.fromDate(createdAt),
        'expiresAt': Timestamp.fromDate(expiresAt),
        'isUsed': isUsed,
      };
}
