// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/providers/ai_chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:friendsheet/data/models/buddy_context.dart' as _i2;
import 'package:friendsheet/data/models/chat_message.dart' as _i5;
import 'package:friendsheet/data/models/meeting.dart' as _i8;
import 'package:friendsheet/data/services/buddy_write_service.dart' as _i9;
import 'package:friendsheet/data/services/context_builder_service.dart' as _i6;
import 'package:friendsheet/data/services/open_ai_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBuddyContext_0 extends _i1.SmartFake implements _i2.BuddyContext {
  _FakeBuddyContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i3.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<String> sendMessage(
    String? contextPrompt,
    List<_i5.ChatMessage>? history,
    String? userMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            contextPrompt,
            history,
            userMessage,
          ],
        ),
        returnValue: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);
}

/// A class which mocks [ContextBuilderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextBuilderService extends _i1.Mock
    implements _i6.ContextBuilderService {
  MockContextBuilderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BuddyContext> buildFullContext(
    String? userId, {
    DateTime? from,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildFullContext,
          [userId],
          {#from: from},
        ),
        returnValue: _i4.Future<_i2.BuddyContext>.value(_FakeBuddyContext_0(
          this,
          Invocation.method(
            #buildFullContext,
            [userId],
            {#from: from},
          ),
        )),
      ) as _i4.Future<_i2.BuddyContext>);

  @override
  _i4.Future<_i2.BuddyContext> buildPersonContext(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPersonContext,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i4.Future<_i2.BuddyContext>.value(_FakeBuddyContext_0(
          this,
          Invocation.method(
            #buildPersonContext,
            [
              userId,
              personId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BuddyContext>);

  @override
  _i4.Future<_i2.BuddyContext> buildBirthdayContext(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildBirthdayContext,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i4.Future<_i2.BuddyContext>.value(_FakeBuddyContext_0(
          this,
          Invocation.method(
            #buildBirthdayContext,
            [
              userId,
              personId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BuddyContext>);

  @override
  String serializeToPrompt(
    _i2.BuddyContext? context, {
    bool? includeNotes = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #serializeToPrompt,
          [context],
          {#includeNotes: includeNotes},
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #serializeToPrompt,
            [context],
            {#includeNotes: includeNotes},
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i8.Meeting?> getMeetingById(
    String? userId,
    String? meetingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingById,
          [
            userId,
            meetingId,
          ],
        ),
        returnValue: _i4.Future<_i8.Meeting?>.value(),
      ) as _i4.Future<_i8.Meeting?>);

  @override
  _i4.Future<_i8.Meeting?> findMostRecentMeetingWithoutNotes(
    String? userId, {
    int? withinDays = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMostRecentMeetingWithoutNotes,
          [userId],
          {#withinDays: withinDays},
        ),
        returnValue: _i4.Future<_i8.Meeting?>.value(),
      ) as _i4.Future<_i8.Meeting?>);
}

/// A class which mocks [BuddyWriteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuddyWriteService extends _i1.Mock implements _i9.BuddyWriteService {
  MockBuddyWriteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveNotes(
    String? userId,
    String? meetingId,
    List<String>? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNotes,
          [
            userId,
            meetingId,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
