// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/providers/calendar_settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:friendsheet/data/models/google_calendar.dart' as _i4;
import 'package:friendsheet/data/services/google_calendar_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleCalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleCalendarService extends _i1.Mock
    implements _i2.GoogleCalendarService {
  MockGoogleCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.GoogleCalendar>> requestAccess() => (super.noSuchMethod(
        Invocation.method(
          #requestAccess,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.GoogleCalendar>>.value(<_i4.GoogleCalendar>[]),
      ) as _i3.Future<List<_i4.GoogleCalendar>>);

  @override
  _i3.Future<List<_i4.GoogleCalendar>> fetchCalendars() => (super.noSuchMethod(
        Invocation.method(
          #fetchCalendars,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.GoogleCalendar>>.value(<_i4.GoogleCalendar>[]),
      ) as _i3.Future<List<_i4.GoogleCalendar>>);

  @override
  _i3.Future<void> revokeAccess() => (super.noSuchMethod(
        Invocation.method(
          #revokeAccess,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
