// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/providers/shared_package_inbox_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:friendsheet/data/models/meeting.dart' as _i7;
import 'package:friendsheet/data/models/pending_meeting_package.dart' as _i4;
import 'package:friendsheet/data/repositories/cache_invalidator.dart' as _i6;
import 'package:friendsheet/data/repositories/meeting_repository.dart' as _i5;
import 'package:friendsheet/data/repositories/pending_meeting_package_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PendingMeetingPackageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPendingMeetingPackageRepository extends _i1.Mock
    implements _i2.PendingMeetingPackageRepository {
  MockPendingMeetingPackageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PendingMeetingPackage>> fetchPackages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPackages,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.PendingMeetingPackage>>.value(
            <_i4.PendingMeetingPackage>[]),
      ) as _i3.Future<List<_i4.PendingMeetingPackage>>);

  @override
  _i3.Future<void> deletePackage(
    String? userId,
    String? packageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePackage,
          [
            userId,
            packageId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i5.MeetingRepository {
  MockMeetingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i6.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String> saveMeeting(_i7.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #saveMeeting,
          [meeting],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #saveMeeting,
            [meeting],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<List<_i7.Meeting>> getMeetingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByUser,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i7.Meeting>>.empty(),
      ) as _i3.Stream<List<_i7.Meeting>>);

  @override
  _i3.Future<void> updateMeeting(_i7.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [meeting],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMeeting(
    String? userId,
    String? meetingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [
            userId,
            meetingId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Meeting>> getMeetingsByParticipant(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByParticipant,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i3.Future<List<_i7.Meeting>>.value(<_i7.Meeting>[]),
      ) as _i3.Future<List<_i7.Meeting>>);

  @override
  _i3.Future<int> getMeetingsCountForPerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsCountForPerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> removePersonFromMeetings(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePersonFromMeetings,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
