// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/providers/statistics_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:friendsheet/data/models/meeting.dart' as _i4;
import 'package:friendsheet/data/repositories/statistics_repository.dart'
    as _i2;
import 'package:friendsheet/data/services/auth_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i2.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<int>> getAvailableYears(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableYears,
          [userId],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<_i4.Meeting>> getMeetingsForYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsForYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Meeting>>.value(<_i4.Meeting>[]),
      ) as _i3.Future<List<_i4.Meeting>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i6.User?>.empty(),
      ) as _i3.Stream<_i6.User?>);

  @override
  _i3.Future<_i6.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i6.User?>.value(),
      ) as _i3.Future<_i6.User?>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
