// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/providers/statistics_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:friendsheet/data/models/activity_category.dart' as _i2;
import 'package:friendsheet/data/models/meeting.dart' as _i6;
import 'package:friendsheet/data/models/person.dart' as _i3;
import 'package:friendsheet/data/repositories/activity_category_repository.dart'
    as _i9;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i10;
import 'package:friendsheet/data/repositories/statistics_repository.dart'
    as _i4;
import 'package:friendsheet/data/services/auth_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeActivityCategory_0 extends _i1.SmartFake
    implements _i2.ActivityCategory {
  _FakeActivityCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerson_1 extends _i1.SmartFake implements _i3.Person {
  _FakePerson_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i4.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<int>> getAvailableYears(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableYears,
          [userId],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<List<_i6.Meeting>> getMeetingsForYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsForYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Meeting>>.value(<_i6.Meeting>[]),
      ) as _i5.Future<List<_i6.Meeting>>);

  @override
  _i5.Future<List<_i4.ActivityBreakdownEntry>> getActivityWeightBreakdown(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityWeightBreakdown,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i4.ActivityBreakdownEntry>>.value(
            <_i4.ActivityBreakdownEntry>[]),
      ) as _i5.Future<List<_i4.ActivityBreakdownEntry>>);

  @override
  _i5.Future<List<_i4.PersonActivityEntry>> getPersonsForActivity(
    String? categoryId,
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsForActivity,
          [
            categoryId,
            year,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i4.PersonActivityEntry>>.value(
            <_i4.PersonActivityEntry>[]),
      ) as _i5.Future<List<_i4.PersonActivityEntry>>);

  @override
  _i5.Future<List<_i4.InteractionDistributionEntry>> getInteractionDistribution(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInteractionDistribution,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i4.InteractionDistributionEntry>>.value(
            <_i4.InteractionDistributionEntry>[]),
      ) as _i5.Future<List<_i4.InteractionDistributionEntry>>);

  @override
  _i5.Future<List<_i4.InteractionDistributionEntry>> getCumulativeInteractions(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCumulativeInteractions,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i4.InteractionDistributionEntry>>.value(
            <_i4.InteractionDistributionEntry>[]),
      ) as _i5.Future<List<_i4.InteractionDistributionEntry>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i8.User?>.empty(),
      ) as _i5.Stream<_i8.User?>);

  @override
  _i5.Future<_i8.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i8.User?>.value(),
      ) as _i5.Future<_i8.User?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ActivityCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityCategoryRepository extends _i1.Mock
    implements _i9.ActivityCategoryRepository {
  MockActivityCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.ActivityCategory>> getCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i2.ActivityCategory>>.empty(),
      ) as _i5.Stream<List<_i2.ActivityCategory>>);

  @override
  _i5.Future<void> addCategory(_i2.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCategory(_i2.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCategory(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWithChildren(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWithChildren,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.ActivityCategory> createSelectableCategory({
    required String? name,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSelectableCategory,
          [],
          {
            #name: name,
            #userId: userId,
          },
        ),
        returnValue:
            _i5.Future<_i2.ActivityCategory>.value(_FakeActivityCategory_0(
          this,
          Invocation.method(
            #createSelectableCategory,
            [],
            {
              #name: name,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i2.ActivityCategory>);

  @override
  _i5.Future<List<_i2.ActivityCategory>> getSelectableCategories(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableCategories,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.ActivityCategory>>.value(
            <_i2.ActivityCategory>[]),
      ) as _i5.Future<List<_i2.ActivityCategory>>);

  @override
  _i5.Future<List<String>> getAncestorIds(
    String? categoryId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestorIds,
          [
            categoryId,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i2.ActivityCategory>> getAllCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.ActivityCategory>>.value(
            <_i2.ActivityCategory>[]),
      ) as _i5.Future<List<_i2.ActivityCategory>>);

  @override
  _i5.Future<List<_i2.ActivityCategory>> getCategoriesByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i2.ActivityCategory>>.value(
            <_i2.ActivityCategory>[]),
      ) as _i5.Future<List<_i2.ActivityCategory>>);
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i10.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.Person>>.value(<_i3.Person>[]),
      ) as _i5.Future<List<_i3.Person>>);

  @override
  _i5.Future<_i3.Person> addPerson(_i3.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i5.Future<_i3.Person>.value(_FakePerson_1(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i5.Future<_i3.Person>);

  @override
  _i5.Future<List<_i3.Person>> getPersonsByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Person>>.value(<_i3.Person>[]),
      ) as _i5.Future<List<_i3.Person>>);

  @override
  _i5.Future<void> updatePerson(_i3.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
