// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/widgets/meeting_date_field_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i11;
import 'package:friendsheet/data/models/activity.dart' as _i3;
import 'package:friendsheet/data/models/meeting.dart' as _i8;
import 'package:friendsheet/data/models/person.dart' as _i2;
import 'package:friendsheet/data/repositories/activity_repository.dart' as _i6;
import 'package:friendsheet/data/repositories/meeting_repository.dart' as _i7;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i4;
import 'package:friendsheet/data/services/auth_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePerson_0 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivity_1 extends _i1.SmartFake implements _i3.Activity {
  _FakeActivity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i4.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i5.Future<List<_i2.Person>>);

  @override
  _i5.Future<_i2.Person> addPerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i5.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i5.Future<_i2.Person>);

  @override
  _i5.Future<List<_i2.Person>> getPersonsByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i5.Future<List<_i2.Person>>);

  @override
  _i5.Future<void> updatePerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i6.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Activity>> getActivitiesByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitiesByUser,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.Activity>>.value(<_i3.Activity>[]),
      ) as _i5.Future<List<_i3.Activity>>);

  @override
  _i5.Future<_i3.Activity> addActivity({
    required String? userId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addActivity,
          [],
          {
            #userId: userId,
            #name: name,
          },
        ),
        returnValue: _i5.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #addActivity,
            [],
            {
              #userId: userId,
              #name: name,
            },
          ),
        )),
      ) as _i5.Future<_i3.Activity>);

  @override
  _i5.Future<List<_i3.Activity>> getActivitiesByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitiesByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i3.Activity>>.value(<_i3.Activity>[]),
      ) as _i5.Future<List<_i3.Activity>>);
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i7.MeetingRepository {
  MockMeetingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #saveMeeting,
          [meeting],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #saveMeeting,
            [meeting],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Stream<List<_i8.Meeting>> getMeetingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByUser,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i8.Meeting>>.empty(),
      ) as _i5.Stream<List<_i8.Meeting>>);

  @override
  _i5.Future<void> updateMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [meeting],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMeeting(String? meetingId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [meetingId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getMeetingsCountForPerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsCountForPerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> removePersonFromMeetings(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePersonFromMeetings,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i11.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i11.User?>.empty(),
      ) as _i5.Stream<_i11.User?>);

  @override
  _i5.Future<_i11.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
