// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/widgets/meeting_date_field_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i11;
import 'package:friendsheet/data/models/activity_category.dart' as _i6;
import 'package:friendsheet/data/models/meeting.dart' as _i8;
import 'package:friendsheet/data/models/person.dart' as _i2;
import 'package:friendsheet/data/repositories/activity_category_repository.dart'
    as _i5;
import 'package:friendsheet/data/repositories/meeting_repository.dart' as _i7;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i3;
import 'package:friendsheet/data/services/auth_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePerson_0 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i3.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<_i2.Person> addPerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i4.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i4.Future<_i2.Person>);

  @override
  _i4.Future<List<_i2.Person>> getPersonsByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [ids],
        ),
        returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<void> updatePerson(_i2.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ActivityCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityCategoryRepository extends _i1.Mock
    implements _i5.ActivityCategoryRepository {
  MockActivityCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i6.ActivityCategory>> getCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i6.ActivityCategory>>.empty(),
      ) as _i4.Stream<List<_i6.ActivityCategory>>);

  @override
  _i4.Future<void> addCategory(_i6.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCategory(_i6.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.ActivityCategory>> getSelectableCategories(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableCategories,
          [userId],
        ),
        returnValue: _i4.Future<List<_i6.ActivityCategory>>.value(
            <_i6.ActivityCategory>[]),
      ) as _i4.Future<List<_i6.ActivityCategory>>);

  @override
  _i4.Future<List<String>> getAncestorIds(
    String? categoryId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestorIds,
          [
            categoryId,
            userId,
          ],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i6.ActivityCategory>> getAllCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [userId],
        ),
        returnValue: _i4.Future<List<_i6.ActivityCategory>>.value(
            <_i6.ActivityCategory>[]),
      ) as _i4.Future<List<_i6.ActivityCategory>>);

  @override
  _i4.Future<List<_i6.ActivityCategory>> getCategoriesByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i4.Future<List<_i6.ActivityCategory>>.value(
            <_i6.ActivityCategory>[]),
      ) as _i4.Future<List<_i6.ActivityCategory>>);
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i7.MeetingRepository {
  MockMeetingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> saveMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #saveMeeting,
          [meeting],
        ),
        returnValue: _i4.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #saveMeeting,
            [meeting],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Stream<List<_i8.Meeting>> getMeetingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsByUser,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i8.Meeting>>.empty(),
      ) as _i4.Stream<List<_i8.Meeting>>);

  @override
  _i4.Future<void> updateMeeting(_i8.Meeting? meeting) => (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [meeting],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMeeting(String? meetingId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMeeting,
          [meetingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getMeetingsCountForPerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsCountForPerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> removePersonFromMeetings(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePersonFromMeetings,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i11.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i11.User?>.empty(),
      ) as _i4.Stream<_i11.User?>);

  @override
  _i4.Future<_i11.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i11.User?>.value(),
      ) as _i4.Future<_i11.User?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
