// Mocks generated by Mockito 5.4.6 from annotations
// in friendsheet/test/presentation/widgets/statistics_section_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:friendsheet/data/models/activity_category.dart' as _i3;
import 'package:friendsheet/data/models/meeting.dart' as _i7;
import 'package:friendsheet/data/models/person.dart' as _i4;
import 'package:friendsheet/data/models/stats_data_bundle.dart' as _i2;
import 'package:friendsheet/data/repositories/activity_category_repository.dart'
    as _i10;
import 'package:friendsheet/data/repositories/cache_invalidator.dart' as _i11;
import 'package:friendsheet/data/repositories/person_repository.dart' as _i12;
import 'package:friendsheet/data/repositories/statistics_repository.dart'
    as _i5;
import 'package:friendsheet/data/services/auth_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatsDataBundle_0 extends _i1.SmartFake
    implements _i2.StatsDataBundle {
  _FakeStatsDataBundle_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityCategory_1 extends _i1.SmartFake
    implements _i3.ActivityCategory {
  _FakeActivityCategory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerson_2 extends _i1.SmartFake implements _i4.Person {
  _FakePerson_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i5.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> invalidateMeetingsCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateMeetingsCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> invalidateCategoriesCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateCategoriesCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> invalidatePersonsCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidatePersonsCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> invalidateAllCaches() => (super.noSuchMethod(
        Invocation.method(
          #invalidateAllCaches,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<int>> getAvailableYears(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableYears,
          [userId],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i7.Meeting>> getMeetingsForYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetingsForYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i6.Future<List<_i7.Meeting>>.value(<_i7.Meeting>[]),
      ) as _i6.Future<List<_i7.Meeting>>);

  @override
  _i6.Future<_i2.StatsDataBundle> loadAllStatsData(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAllStatsData,
          [
            year,
            userId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.StatsDataBundle>.value(_FakeStatsDataBundle_0(
          this,
          Invocation.method(
            #loadAllStatsData,
            [
              year,
              userId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.StatsDataBundle>);

  @override
  List<_i5.ActivityBreakdownEntry> computeActivityBreakdown(
          _i2.StatsDataBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeActivityBreakdown,
          [bundle],
        ),
        returnValue: <_i5.ActivityBreakdownEntry>[],
      ) as List<_i5.ActivityBreakdownEntry>);

  @override
  List<_i5.PersonActivityEntry> computePersonsForActivity(
    _i2.StatsDataBundle? bundle,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #computePersonsForActivity,
          [
            bundle,
            categoryId,
          ],
        ),
        returnValue: <_i5.PersonActivityEntry>[],
      ) as List<_i5.PersonActivityEntry>);

  @override
  List<_i5.InteractionDistributionEntry> computeInteractionDistribution(
          _i2.StatsDataBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeInteractionDistribution,
          [bundle],
        ),
        returnValue: <_i5.InteractionDistributionEntry>[],
      ) as List<_i5.InteractionDistributionEntry>);

  @override
  _i6.Future<List<_i5.ActivityBreakdownEntry>> getActivityWeightBreakdown(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityWeightBreakdown,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i5.ActivityBreakdownEntry>>.value(
            <_i5.ActivityBreakdownEntry>[]),
      ) as _i6.Future<List<_i5.ActivityBreakdownEntry>>);

  @override
  _i6.Future<List<_i5.PersonActivityEntry>> getPersonsForActivity(
    String? categoryId,
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsForActivity,
          [
            categoryId,
            year,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i5.PersonActivityEntry>>.value(
            <_i5.PersonActivityEntry>[]),
      ) as _i6.Future<List<_i5.PersonActivityEntry>>);

  @override
  _i6.Future<List<_i5.InteractionDistributionEntry>> getInteractionDistribution(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInteractionDistribution,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i5.InteractionDistributionEntry>>.value(
            <_i5.InteractionDistributionEntry>[]),
      ) as _i6.Future<List<_i5.InteractionDistributionEntry>>);

  @override
  _i6.Future<List<_i5.InteractionDistributionEntry>> getCumulativeInteractions(
    int? year,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCumulativeInteractions,
          [
            year,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i5.InteractionDistributionEntry>>.value(
            <_i5.InteractionDistributionEntry>[]),
      ) as _i6.Future<List<_i5.InteractionDistributionEntry>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i9.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i9.User?>.empty(),
      ) as _i6.Stream<_i9.User?>);

  @override
  _i6.Future<_i9.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i6.Future<_i9.User?>.value(),
      ) as _i6.Future<_i9.User?>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> runOnboardingIfNeeded(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #runOnboardingIfNeeded,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> copyGlobalCategoriesToUserForTest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyGlobalCategoriesToUserForTest,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ActivityCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityCategoryRepository extends _i1.Mock
    implements _i10.ActivityCategoryRepository {
  MockActivityCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i11.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<List<_i3.ActivityCategory>> getCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i3.ActivityCategory>>.empty(),
      ) as _i6.Stream<List<_i3.ActivityCategory>>);

  @override
  _i6.Future<void> addCategory(_i3.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateCategory(_i3.ActivityCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCategory(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWithChildren(
    String? userId,
    String? categoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWithChildren,
          [
            userId,
            categoryId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.ActivityCategory> createSelectableCategory({
    required String? name,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSelectableCategory,
          [],
          {
            #name: name,
            #userId: userId,
          },
        ),
        returnValue:
            _i6.Future<_i3.ActivityCategory>.value(_FakeActivityCategory_1(
          this,
          Invocation.method(
            #createSelectableCategory,
            [],
            {
              #name: name,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<_i3.ActivityCategory>);

  @override
  _i6.Future<List<_i3.ActivityCategory>> getSelectableCategories(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableCategories,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i6.Future<List<_i3.ActivityCategory>>);

  @override
  _i6.Future<List<String>> getAncestorIds(
    String? categoryId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestorIds,
          [
            categoryId,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<List<_i3.ActivityCategory>> getAllCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i6.Future<List<_i3.ActivityCategory>>);

  @override
  _i6.Future<List<_i3.ActivityCategory>> getCategoriesByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i3.ActivityCategory>>.value(
            <_i3.ActivityCategory>[]),
      ) as _i6.Future<List<_i3.ActivityCategory>>);
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i12.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cacheInvalidator(_i11.CacheInvalidator? _cacheInvalidator) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheInvalidator,
          _cacheInvalidator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i4.Person>> getPersonsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByUser,
          [userId],
        ),
        returnValue: _i6.Future<List<_i4.Person>>.value(<_i4.Person>[]),
      ) as _i6.Future<List<_i4.Person>>);

  @override
  _i6.Future<_i4.Person> addPerson(_i4.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #addPerson,
          [person],
        ),
        returnValue: _i6.Future<_i4.Person>.value(_FakePerson_2(
          this,
          Invocation.method(
            #addPerson,
            [person],
          ),
        )),
      ) as _i6.Future<_i4.Person>);

  @override
  _i6.Future<List<_i4.Person>> getPersonsByIds(
    List<String>? ids,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsByIds,
          [
            ids,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i4.Person>>.value(<_i4.Person>[]),
      ) as _i6.Future<List<_i4.Person>>);

  @override
  _i6.Future<void> updatePerson(_i4.Person? person) => (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [person],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isDuplicateName(
    String? userId,
    String? firstName,
    String? lastName, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateName,
          [
            userId,
            firstName,
            lastName,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> deletePerson(
    String? userId,
    String? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [
            userId,
            personId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
